### PR TITLE
User data management

### PR DESCRIPTION
**Pull request by iansteyn**
### Main Additions
This branch updates the `User` class and adds the class `UserList`. Both have JavaDoc comments at the top that you can read. 

`UserList` is a super simple class that provides access to User objects in our "database" with the method `UserList.get(userId)`. The current user can be identified with `UserList.CURRENT_USER_ID`.

`User` objects have usernames and associated profile pictures. They store the variable `profilePicId`, which is the resource id for the corresponding profile picture stored in the `drawable` folder of our app. 

### Other Stuff
Other things worked on in this branch, which remain unfinished:
- started updating `addFakePosts` to be have more realistic, interesting posts for when we do the demo.
- added some images in the drawable folder I plan on using for #5 and #34

### CODE REVIEW

**Review by TylerSchaus — COMMENTED** [review]
Overall looks great, no major concerns. 

**Some things to note:**

- Might want to review the criteria, I vaguely remember some mention that creating / adding a user should be included, albeit not a main class. 

This is more so a concern I have just thought of relating to User. 
- If it is necessary such that the program can be closed and reloaded and maintain the correct display, it will be problematic that a users _liked_ and _disliked_ posts are not saved. This is just because upon reload, there would be nothing preventing the same user from liking/disliking the same post again. The logic to prevent in the same session is handled in the FeedFragment, but never saved. 
Just a thought.

**Comment by TylerSchaus** [comment]
Just reread my review and noticed a typo. I meant *albeit not a main task*. Also the only reason that would be an issue is because the UserList is read only. Again, very likely I'm just trippin and this is not required.

**Comment by iansteyn** [comment]
@TylerSchaus 

> * Might want to review the criteria, I vaguely remember some mention that creating / adding a user should be included, albeit not a main class.

I checked both the Project Step 4 instructions and our own requirements from Step 2. I can't find any reference to this. We may have discussed the possibility at some point because it seems like such a natural thing for an app to be able to do, but I think we're fine to keep it static for the purposes of our delivering this project.

**Comment by iansteyn** [comment]
image

Just putting this here for documentation purposes lol. Will add save feature for likes/dislikes.

**Comment by iansteyn** [comment]
### New Additions to `Post`

Removed the `numLikes` and `numDislikes` attributes and replaced them with LinkedLists called `likedBy` and `dislikedBy`. These store the userIds of users who have liked and dislike the post. They cannot be directly accessed, not even with getters. Instead, there are a few helpful methods:
- `getNumLikes()` and `getNumDislikes()`  return the size of their respective lists
- `isLikedBy(userId)` and `isDislikedBy(userId)` return true if a user has liked/disliked this post

Updated methods:
- `addLike` and `addDislike` now take a `userId` as an argument. A user will only be added to the like/dislike list if they are not already in it. These methods also remove the user from the other list.
- `removeLike` and `removeDislike` also take `userId` as an argument. They will remove a user from the like/dislike list. If the user is not in the list to begin with, they do nothing (but will not cause an error).

**Review by TylerSchaus — COMMENTED** [review]
All looks good to me. Should fix remaining issues with reloading the app and having all data correctly saved.

**Review by TylerSchaus — APPROVED** [review]
All good.

**Pull request merged**
